schema_version = "1.0.0"

id = "erosion_terrain_extension"
version = "1.0.0"
name = "Erosion terrain generator"
tagline = "An erosion based terrain generator"
maintainer = "Lucas Frans Willem Furer"
type = "add-on"

website = "https://github.com/LucasFurer/my_blender_addon"

tags = ["Add Mesh"]

copyright = [
  "2026 Lucas Frans Willem Furer",
]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
